const DATASET_VERSION = '1.0';

const accounts = [
  {
    legacyId: 1,
    key: 'primary',
    name: 'Primary Checking',
    owner: 'Alex',
    account_type: 'Checking',
    amount: 8200,
    date: '2026-01-01',
    notes: 'Main household cash account',
    active: true,
  },
  {
    legacyId: 2,
    key: 'emergency',
    name: 'Emergency Savings',
    owner: 'Alex',
    account_type: 'Savings',
    amount: 14500,
    date: '2026-01-01',
    notes: 'Emergency reserve',
    active: true,
  },
  {
    legacyId: 3,
    key: 'vacation',
    name: 'Vacation Savings',
    owner: 'Jordan',
    account_type: 'Savings',
    amount: 3600,
    date: '2026-01-01',
    notes: 'Short-term travel fund',
    active: true,
  },
  {
    legacyId: 4,
    key: 'joint',
    name: 'Joint Checking',
    owner: 'Joint',
    account_type: 'Checking',
    amount: 4100,
    date: '2026-01-01',
    notes: 'Shared bills account',
    active: true,
  },
];

const incomeSources = [
  {
    legacyId: 1,
    accountKey: 'primary',
    is_account_transfer: false,
    label: 'Primary Salary',
    amount: 6400,
    start_date: '2026-01-01',
    end_date: null,
    frequency: 'monthly',
    notes: 'Monthly net payroll',
    active: true,
  },
  {
    legacyId: 2,
    accountKey: 'joint',
    is_account_transfer: false,
    label: 'Partner Salary',
    amount: 4200,
    start_date: '2026-01-01',
    end_date: null,
    frequency: 'monthly',
    notes: 'Monthly net payroll',
    active: true,
  },
  {
    legacyId: 3,
    accountKey: 'primary',
    is_account_transfer: false,
    label: 'Side Consulting',
    amount: 850,
    start_date: '2026-02-01',
    end_date: null,
    frequency: 'monthly',
    notes: 'Recurring client retainer',
    active: true,
  },
  {
    legacyId: 4,
    accountKey: 'emergency',
    is_account_transfer: false,
    label: 'Annual Bonus',
    amount: 3000,
    start_date: '2026-06-01',
    end_date: null,
    frequency: 'one_time',
    notes: 'One-time annual bonus',
    active: true,
  },
  {
    legacyId: 5,
    is_account_transfer: true,
    fromAccountKey: 'primary',
    toAccountKey: 'vacation',
    label: 'Vacation Savings Transfer',
    amount: 300,
    start_date: '2026-01-01',
    end_date: null,
    frequency: 'monthly',
    notes: 'Monthly savings transfer',
    active: true,
  },
];

const debts = [
  {
    legacyId: 1,
    accountKey: 'primary',
    name: 'Travel Rewards Card',
    debt_type: 'credit_card',
    starting_balance: 4800,
    current_balance: 4800,
    minimum_monthly_payment: 125,
    planned_extra_payment: 175,
    recurrence: null,
    payment_due_day: null,
    payment_date: '2026-01-15',
    start_date: '2026-01-01',
    payoff_target_date: null,
    priority_number: 1,
    active: true,
    notes: 'High-interest card targeted first',
  },
  {
    legacyId: 2,
    accountKey: 'joint',
    name: 'Family Auto Loan',
    debt_type: 'vehicle_loan',
    starting_balance: 18500,
    current_balance: 18500,
    minimum_monthly_payment: 435,
    planned_extra_payment: 0,
    recurrence: null,
    payment_due_day: null,
    payment_date: '2026-01-20',
    start_date: '2026-01-01',
    payoff_target_date: null,
    priority_number: 3,
    active: true,
    notes: null,
  },
  {
    legacyId: 3,
    accountKey: 'primary',
    name: 'Home Improvement Loan',
    debt_type: 'personal_loan',
    starting_balance: 9200,
    current_balance: 9200,
    minimum_monthly_payment: 285,
    planned_extra_payment: 65,
    recurrence: null,
    payment_due_day: null,
    payment_date: '2026-01-10',
    start_date: '2026-01-01',
    payoff_target_date: null,
    priority_number: 2,
    active: true,
    notes: null,
  },
  {
    legacyId: 4,
    accountKey: 'joint',
    name: 'Graduate Student Loan',
    debt_type: 'student_loan',
    starting_balance: 14200,
    current_balance: 14200,
    minimum_monthly_payment: 210,
    planned_extra_payment: 0,
    recurrence: null,
    payment_due_day: null,
    payment_date: '2026-01-05',
    start_date: '2026-01-01',
    payoff_target_date: null,
    priority_number: 4,
    active: true,
    notes: null,
  },
  {
    legacyId: 5,
    accountKey: 'joint',
    name: 'Utilities',
    debt_type: 'other',
    starting_balance: 0,
    current_balance: 0,
    minimum_monthly_payment: 360,
    planned_extra_payment: 0,
    recurrence: 'monthly',
    payment_due_day: null,
    payment_date: null,
    start_date: '2026-01-01',
    payoff_target_date: null,
    priority_number: null,
    active: true,
    notes: 'Monthly household utilities',
  },
  {
    legacyId: 6,
    accountKey: 'primary',
    name: 'Streaming Services',
    debt_type: 'other',
    starting_balance: 0,
    current_balance: 0,
    minimum_monthly_payment: 95,
    planned_extra_payment: 0,
    recurrence: 'monthly',
    payment_due_day: null,
    payment_date: null,
    start_date: '2026-01-01',
    payoff_target_date: null,
    priority_number: null,
    active: true,
    notes: 'Recurring subscriptions',
  },
  {
    legacyId: 7,
    accountKey: 'primary',
    name: 'Auto Insurance',
    debt_type: 'other',
    starting_balance: 0,
    current_balance: 0,
    minimum_monthly_payment: 180,
    planned_extra_payment: 0,
    recurrence: 'monthly',
    payment_due_day: null,
    payment_date: null,
    start_date: '2026-01-01',
    payoff_target_date: null,
    priority_number: null,
    active: true,
    notes: null,
  },
  {
    legacyId: 8,
    accountKey: 'primary',
    name: 'Warehouse Membership',
    debt_type: 'other',
    starting_balance: 0,
    current_balance: 0,
    minimum_monthly_payment: 120,
    planned_extra_payment: 0,
    recurrence: 'one_time',
    payment_due_day: null,
    payment_date: null,
    start_date: '2026-03-01',
    payoff_target_date: null,
    priority_number: null,
    active: true,
    notes: 'Annual membership renewal',
  },
];

const interestRates = [
  {
    legacyId: 1,
    debtName: 'Travel Rewards Card',
    apr_percentage: 0,
    start_date: '2026-01-01',
    end_date: '2026-04-01',
    notes: 'Intro promotional APR',
  },
  {
    legacyId: 2,
    debtName: 'Travel Rewards Card',
    apr_percentage: 22.99,
    start_date: '2026-05-01',
    end_date: null,
    notes: 'Standard APR',
  },
  {
    legacyId: 3,
    debtName: 'Family Auto Loan',
    apr_percentage: 6.4,
    start_date: '2026-01-01',
    end_date: null,
    notes: null,
  },
  {
    legacyId: 4,
    debtName: 'Home Improvement Loan',
    apr_percentage: 10.75,
    start_date: '2026-01-01',
    end_date: null,
    notes: null,
  },
  {
    legacyId: 5,
    debtName: 'Graduate Student Loan',
    apr_percentage: 5.25,
    start_date: '2026-01-01',
    end_date: null,
    notes: null,
  },
];

const savedProjectionAnchors = [
  {
    legacyId: 1,
    key: 'baseline_projection',
    title: 'Demo Household Baseline',
    projection_type: 'baseline',
    role: 'Baseline Projection',
    notes: 'Official Founded portfolio demo baseline.',
    importStatus: 'deferred',
  },
  {
    legacyId: 2,
    key: 'debt_reduction_projection',
    title: 'Demo Debt Reduction Scenario',
    projection_type: 'scenario',
    role: 'Debt Reduction Projection',
    baselineKey: 'baseline_projection',
    notes: 'Adds focused payoff dollars and trims one recurring bill.',
    importStatus: 'deferred',
  },
  {
    legacyId: 3,
    key: 'income_increase_projection',
    title: 'Demo Income Increase Scenario',
    projection_type: 'scenario',
    role: 'Income Increase Projection',
    baselineKey: 'baseline_projection',
    notes: 'Models a promotion and a new monthly retainer.',
    importStatus: 'deferred',
  },
  {
    legacyId: 4,
    key: 'emergency_expense_projection',
    title: 'Demo Emergency Expense Scenario',
    projection_type: 'scenario',
    role: 'Emergency Expense Projection',
    baselineKey: 'baseline_projection',
    notes: 'Adds a one-time household repair expense.',
    importStatus: 'deferred',
  },
];

const validationAnchors = [
  {
    title: 'Demo Household Baseline',
    monthlySurplus: 8670,
    cashBalance: 39070,
    totalDebtBalance: 45648.21,
    totalDebtPayments: 1295,
    bills: 635,
    principal: 1051.79,
    interest: 243.21,
  },
  {
    title: 'Demo Debt Reduction Scenario',
    monthlySurplus: 8405,
    cashBalance: 38805,
    totalDebtBalance: 45348.21,
    totalDebtPayments: 1595,
    bills: 600,
    principal: 1351.79,
    interest: 243.21,
  },
  {
    title: 'Demo Income Increase Scenario',
    monthlySurplus: 9370,
    cashBalance: 39770,
    totalDebtBalance: 45648.21,
    totalDebtPayments: 1295,
    bills: 635,
    principal: 1051.79,
    interest: 243.21,
  },
  {
    title: 'Demo Emergency Expense Scenario',
    monthlySurplus: 8670,
    cashBalance: 39070,
    totalDebtBalance: 45648.21,
    totalDebtPayments: 1295,
    bills: 635,
    principal: 1051.79,
    interest: 243.21,
  },
];

function expectedCounts() {
  return {
    accountBalances: accounts.length,
    incomeSources: incomeSources.length,
    debts: debts.length,
    interestRates: interestRates.length,
    savedProjections: savedProjectionAnchors.length,
    scenarios: savedProjectionAnchors.filter((projection) => projection.projection_type === 'scenario').length,
  };
}

function relationshipCounts() {
  return {
    incomeAccountReferences: incomeSources.filter((source) => source.accountKey).length,
    transferAccountReferences: incomeSources.filter((source) => source.is_account_transfer).length * 2,
    debtAccountReferences: debts.filter((debt) => debt.accountKey).length,
    interestRateDebtReferences: interestRates.length,
    scenarioBaselineReferences: savedProjectionAnchors.filter((projection) => projection.baselineKey).length,
  };
}

function preview() {
  return {
    datasetVersion: DATASET_VERSION,
    targetCollections: {
      accounts: 'accountBalances',
      incomeSources: 'incomeSources',
      debts: 'debts',
      interestRates: 'interestRates',
      savedProjections: 'savedProjections',
      scenarios: 'savedProjections',
    },
    expectedCounts: expectedCounts(),
    relationshipCounts: relationshipCounts(),
    validationAnchors: validationAnchors.map((anchor) => anchor.title),
    importStatus: 'ready',
    importRationale: 'Dataset Version 1.0 is ready for the Phase 8 MongoDB import and validation workflow.',
  };
}

module.exports = {
  DATASET_VERSION,
  accounts,
  incomeSources,
  debts,
  interestRates,
  savedProjectionAnchors,
  validationAnchors,
  expectedCounts,
  relationshipCounts,
  preview,
};
